# Nombre de la aplicacion
spring.application.name=gym-bookings-service
# Puerto HTTP del microservicio
server.port=8080

# Conexion a PostgreSQL (valores por defecto para ejecucion local)
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5436}/${DB_NAME:bookings_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OAuth2 Resource Server - apunta al realm gym-system de Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8280/realms/gym-system

# Logs de depuracion de seguridad y web
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
